### ISSUE TITLE
功能建议:modbus tcp

### ISSUE THREAD

**Issue by lion-brave** [hootrhino/rulex#124]
modbus tcp应该是多路复用，而不是和modbus 485进行轮询，这个地方应该是分组，多并发采集，一般的特别是modbus tcp，会有多组多个采集点，所以这个地方要支持批量上传点位，modbus 485也要支持批量上传，批量导入

**Comment by wwhai** [comment]
此处下个版本会增加一个批量导入的功能
![image](https://github.com/hootrhino/rulex/assets/20577297/c48bc468-b03c-4d0c-afa8-3cf31d46e683)

**Comment by wwhai** [comment]
0.6以后增强，现阶段暂时不处理
