### ISSUE TITLE
新的rulex前端管理页面项目在哪里

### ISSUE THREAD

**Issue by dbsd11** [hootrhino/rulex#155]
没有找到新的rulex前端管理页面，无法体验rulex本地环境功能

**Comment by wwhai** [comment]
前端开发中 暂未公开。需要可进社区拿预览版

**Comment by dbsd11** [comment]
怎么进社区啊

**Comment by wwhai** [comment]
> 怎么进社区啊

http://www.hootrhino.com/communication
