### ISSUE TITLE
发现BUG: etc 网关配置文件路径

### ISSUE THREAD

**Issue by tr1gv0n** [hootrhino/rulex#179]
(https://github.com/hootrhino/rulex/blob/a467480ae6ba5b3390203afc01065aaa667aee55/plugin/http_server/system_config_api.go#L189)

**Comment by wwhai** [comment]
刚发现，即将修复

> (
> 
> https://github.com/hootrhino/rulex/blob/a467480ae6ba5b3390203afc01065aaa667aee55/plugin/http_server/system_config_api.go#L189
> 
> )

## 刚发现，即将修复
