### ISSUE TITLE
发现BUG: 数据校验

### ISSUE THREAD

**Issue by tr1gv0n** [hootrhino/rulex#180]
https://github.com/hootrhino/rulex/blob/a467480ae6ba5b3390203afc01065aaa667aee55/plugin/http_server/system_config_api.go#L110C54-L110C54

这里是允许空值么？

**Comment by wwhai** [comment]
> https://github.com/hootrhino/rulex/blob/a467480ae6ba5b3390203afc01065aaa667aee55/plugin/http_server/system_config_api.go#L110C54-L110C54
> 
> 这里是允许空值么？

这里确实有问题 我换成别的校验函数了，已经解决
