### ISSUE TITLE
发现BUG:编辑设备时，寄存器配置-添加一行数据，Modbus功能码没默认值，应该为“03读保持寄存器”

### ISSUE THREAD

**Issue by qubbei** [hootrhino/rulex#207]
**大致描述**
编辑设备时，寄存器配置-添加一行数据，Modbus功能码没默认值，应该为“03读保持寄存器”
![7c941ddd3539f6fa6ad0a530249e5ac](https://github.com/hootrhino/rulex/assets/65695459/d1faa919-aad7-4251-b955-1315733b8c9b)

**Comment by Evey-huang** [comment]
fixed
