### ISSUE TITLE
数据中心

### ISSUE THREAD

**Issue by renshan1** [hootrhino/rulex#230]
配置完规则没有数据，且点进数据中心的时候顶上有报错
![Snipaste_2024-05-18_21-05-23](https://github.com/hootrhino/rulex/assets/116544776/cae3e6aa-7f0f-415c-b2f9-1dd728d5897d)

**Comment by wwhai** [comment]
![image](https://github.com/hootrhino/rulex/assets/20577297/73c6a33e-2d12-49ba-b861-5c67aa15a06b)
